### PR TITLE
bug: Correction of the flag data type #89

### LINKED ISSUE #89: Debug & melhoramento
# Descrição
Debug do código fonte.

**Prioridades**:
- [x] Encontrar bugs nos módulos (data_cleaning, doc_generator, usable, etc) e na main através de variados casos de teste utilizando o pytest ou qualquer outra biblioteca que acharem útil ou necessária;
- [x] Propor soluções para eliminação dos bugs encontrados;
- [x] Reportar à equipe caso seja preciso realizar uma grande mudança de código; 

## Critérios de Aceitação
- [x] Commits e pull request com descrição das atividades desenvolvidas.

### PR DESCRIPTION
**Pull request by LucasBergholz**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by igorpenhaa — APPROVED** [review]
well done, Gobbi, Bruno and Igor, you guys are amazing

**Review by BrunoRiibeiro — APPROVED** [review]
Well done!

**Review by diogjunior100 — APPROVED** [review]
Well Done !!!

**Review by RafaelN0bre — APPROVED** [review]
Well done Guys !!

**Pull request merged**
