### PR TITLE
Adding constraints to data filtering

### PR DESCRIPTION
**Pull request by brunomartins03**
# Description

I've created a way to set constraints for filtering data according to an evaluate expression through the pandas library.

## Type of change
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# How Has This Been Tested?

I've done some unit tests in my local environment.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by igorpenhaa — APPROVED** [review]
excellent work, bruno!

**Review by LucasBergholz — APPROVED** [review]
Great job guys.

**Review by BrunoRiibeiro — APPROVED** [review]

**Review by diogjunior100 — APPROVED** [review]
Well Done Guys !!!

**Review by RafaelN0bre — APPROVED** [review]
Well done bruno !!

**Pull request merged**
